---
name: Tor
version: dev
slug: tor
description: Protect your privacy and access Home Assistant via Tor
url: https://github.com/hassio-addons/addon-tor
codenotary: codenotary@frenck.dev
startup: services
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
ports:
  9050/tcp: 9050
ports_description:
  9050/tcp: Tor SOCKS proxy port
map:
  - ssl:rw
options:
  socks: false
  hidden_services: true
  stealth: false
  client_names: []
  ports:
    - "8123"
    - "8123:80"
  snowflake_url: "https://snowflake-broker.torproject.net.global.prod.fastly.net/"
  snowflake_front: "cdn.sstatic.net"
  snowflake_ice: 
    - "stun:stun.voip.blackberry.com:3478"
    - "stun:stun.antisip.com:3478"
    - "stun:stun.bluesip.net:3478"
    - "stun:stun.dus.net:3478"
    - "stun:stun.epygi.com:3478"
    - "stun:stun.sonetel.com:3478"
    - "stun:stun.sonetel.net:3478"
    - "stun:stun.uls.co.za:3478"
    - "stun:stun.voipgate.com:3478"
    - "stun:stun.voys.nl:3478"
  bridges:
    - "snowflake 192.0.2.4:80 8838024498816A039FCBBAB14E6F40A0843051FA"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  socks: bool
  hidden_services: bool
  stealth: bool
  client_names:
    - match(^[A-Za-z0-9+-_]{1,16}$)
  ports:
    - match(^(.*:)?(?:[0-9]{1,4}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])?$)
  snowflake_url: url
  snowflake_front: str
  snowflake_ice: 
    - str
  bridges:
    - str