---
name: Tor
version: dev
slug: tor
description: Protect your privacy and access Home Assistant via Tor
url: https://github.com/hassio-addons/addon-tor
codenotary: codenotary@frenck.dev
startup: services
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
ports:
  9050/tcp: 9050
ports_description:
  9050/tcp: Tor SOCKS proxy port
map:
  - ssl:rw
options:
  socks: false
  hidden_services: true
  stealth: false
  client_names: []
  ports:
    - "8123"
    - "8123:80"
  bridges: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  socks: bool
  hidden_services: bool
  stealth: bool
  client_names:
    - match(^[A-Za-z0-9+-_]{1,16}$)
  ports:
    - match(^(.*:)?(?:[0-9]{1,4}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])?$)
  bridges:
    - match(^obfs4 ((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}:((6553[0-5])|(655[0-2][0-9])|(65[0-4][0-9]{2})|(6[0-4][0-9]{3})|([1-5][0-9]{4})|([0-5]{0,5})|([0-9]{1,4}))( \w{40})( cert=\S{70})( iat-mode=[0-2])?$)
